### PR TITLE
check_access can throw KeyError under certain circumstances

### PR DESCRIPTION
**Pull request by 7wonders**
For example on heroku together with newrelic this error will be thrown EVERY time any other server error is thrown. Very frustrating. Simple try/except fixes it.

```
File “/app/.heroku/python/lib/python2.7/site-packages/sitetree/sitetreeapp.py”, line 722, in check_access
    authenticated = self._global_context[‘request’].user.is_authenticated()
  File “/app/.heroku/python/lib/python2.7/site-packages/django/template/context.py”, line 71, in __getitem__
    raise KeyError(key)
KeyError: u’request’
```

### CODE REVIEW

**Comment by idlesign** [comment]
Sorrey for the delay.
That's strange. How does that connected with every other error? What's in global context on such ocassions?

**Comment by chrisjrn** [comment]
I'm seeing this issue too, on all 500 errors. What can I do to help this patch get merged?

**Comment by idlesign** [comment]
@chrisjrn Mainly we need to discover the reason. 
This one might to be related to threads issue addressed in ``feat/thread_context`` branch. You can try code from that and verify whether it is true.

**Comment by idlesign** [comment]
Please check this behaviour is still relevant to 1.7.0.

**Comment by idlesign** [comment]
Similar messages were spotted on low-memory VPS.

**Comment by nakato** [comment]
I've managed to reproduce it on chrisjrn's codebase with version 1.5.1 installed.
The exact error does not occur with 1.7.0 installed, however a similar issue occurs.

I managed to reproduce it by stuffing up INSTALLED_APPS where a Django module I am using attempts to use another Django module that I have not declared in INSTALLED_APPS.

However, I doubt this is how others are triggering it.

This new error shows up after the original 500 error.

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/git/website/ve2/lib/python2.7/site-packages/dj_static.py", line 83, in __call__
    return self.application(environ, start_response)
  File "/home/git/website/ve2/lib/python2.7/site-packages/dj_static.py", line 83, in __call__
    return self.application(environ, start_response)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/core/handlers/base.py", line 296, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/views/defaults.py", line 63, in server_error
    return http.HttpResponseServerError(template.render())
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/sitetree/templatetags/sitetree.py", line 201, in render
    tree_items = get_sitetree().menu(self.tree_alias, self.tree_branches, context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/sitetree/sitetreeapp.py", line 773, in menu
    tree_alias, sitetree_items = self.init_tree(tree_alias, context)
  File "/home/git/website/ve2/lib/python2.7/site-packages/sitetree/sitetreeapp.py", line 705, in init_tree
    'Sitetree requires "django.core.context_processors.request" template context processor to be active. '
SiteTreeError: Sitetree requires "django.core.context_processors.request" template context processor to be active. If it is, check that your view pushes request data into the template.
```

**Pull request closed without merging**
