### PR TITLE
Added IGNORE_ADMIN_APP to settings

### PR DESCRIPTION
**Pull request by ar4s**
I customized admin panel and I replaced standard django menu system by sitetree and I need this change for correctly display menu items when user have limited permissions.

### CODE REVIEW

**Comment by idlesign** [comment]
Do you mean that you need to restrict tree items access for admin users?
If so, how do you plan to differentiate calls to render admin nav and to render tree editor items (some tree items could be anavailable in this case)?

**Comment by ar4s** [comment]
In my case admin panel is base tool for all users, but have different permission and use sitetree only for show menu - menu editor is irrelevant in this case.

**Comment by idlesign** [comment]
I see. It seems that we need something similar to SITETREE_ADMIN_APP_NAME setting to cover more use cases (e.g. admin app overriden). So that at https://github.com/idlesign/django-sitetree/blob/master/sitetree/sitetreeapp.py#L417 we check against SITETREE_ADMIN_APP_NAME.
For your use case any name will do.

**Comment by idlesign** [comment]
Partially implemented in ecdbc7f0c8b33743e0b855cbd5c3a61796e3c8da.
Considered closed. 
Feel free to reopen if required.

**Pull request closed without merging**
