### PR TITLE
Adds an IGNORE_ERRORS setting

### PR DESCRIPTION
**Pull request by 7wonders**
There are some cases where it is rather annoying to get reminded about missing sitetree items even in a debug environment. This adds a simple SITETREE_IGNORE_ERRORS setting that will not throw the "No resolved sitetree item..." error.

### CODE REVIEW

**Comment by idlesign** [comment]
Can you name those cases, when such errors can annoy in debug mode?
Also we'll need a more descriptive title (e.g. RAISE_ITEMS_ERRORS_ON_DEBUG), and mentioning that setting in docs.

**Comment by 7wonders** [comment]
Well, my case is developing based off a pg_dump of production and need to keep restoring the db in between knowing/making the initial changes to my site trees and pushing to staging/production. As I have sitetree in the main layout my setup is expected to have a sitetree entry for all public pages and the errors just slow things down. This way I can do all the changes I need in dev then turn the errors back on during checking and testing. I will make the changes you suggested and repush.

**Comment by idlesign** [comment]
Ready and waiting %)

**Comment by 7wonders** [comment]
Sorry for the delay :)

**Comment by idlesign** [comment]
Thank you. Merged. 
Although test improvements would be nice %)

**Pull request merged**
