### PR TITLE
fix #257 and test various url patterns

### LINKED ISSUE #257: Wrong value in URL is irreversible in Admin
I filled `template-addons'` value in `TemplateItem` `URL` field and enabled `URL as Pattern`. It resulted in broken admin, so I couldn't correct the value without using console (which is quite severe, because it could lead to long downtime, if the user editing hadn't the ability to use console).
The wrong value also broke the page where the menu was rendered (which I consider much less severe bug, because if I was able to edit it in admin I could fix it immediately).

The error is following:
```
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/lib/python3.6/site-packages/django/core/handlers/base.py", line 119, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/lib/python3.6/site-packages/debug_toolbar/middleware.py", line 84, in process_view
    response = panel.process_view(request, view_func, view_args, view_kwargs)
  File "/lib/python3.6/site-packages/debug_toolbar/panels/profiling.py", line 155, in process_view
    return self.profiler.runcall(view_func, *args, **view_kwargs)
  File "/usr/lib/python3.6/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/lib/python3.6/site-packages/sitetree/admin.py", line 222, in item_edit
    return self.change_view(request, item_id, extra_context={'tree': tree})
  File "/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1557, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1451, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1480, in _changeform_view
    ModelForm = self.get_form(request, obj)
  File "/lib/python3.6/site-packages/sitetree/admin.py", line 173, in get_form
    my_choice_field = TreeItemChoiceField(self.tree, initial=previous_parent_id)
  File "/lib/python3.6/site-packages/sitetree/fields.py", line 38, in __init__
    self.choices = self._build_choices()
  File "/lib/python3.6/site-packages/sitetree/fields.py", line 50, in _build_choices
    ).render(context)
  File "/lib/python3.6/site-packages/sitetree/templatetags/sitetree.py", line 164, in render
    tree_items = get_sitetree().tree(self.tree_alias, context)
  File "/lib/python3.6/site-packages/sitetree/sitetreeapp.py", line 953, in tree
    tree_alias, sitetree_items = self.init_tree(tree_alias, context)
  File "/lib/python3.6/site-packages/sitetree/sitetreeapp.py", line 732, in init_tree
    tree_alias, sitetree_items = self.get_sitetree(tree_alias)
  File "/lib/python3.6/site-packages/sitetree/sitetreeapp.py", line 567, in get_sitetree
    item.url_resolved = url(item)
  File "/lib/python3.6/site-packages/sitetree/sitetreeapp.py", line 697, in url
    Token(token_type=TOKEN_BLOCK, contents=url_token)
  File "/lib/python3.6/site-packages/django/template/defaulttags.py", line 1381, in url
    args.append(parser.compile_filter(value))
  File "/lib/python3.6/site-packages/django/template/base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "/lib/python3.6/site-packages/django/template/base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''' from '''
```

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by idlesign** [comment]
Sorry can't accept it there's probably a ton of symbols that can brake Admin, besides, it seems that a URL resolution makes no sense in Admin at all.
We probably need to use ``current_app_is_admin`` or something similar.

**Comment by PetrDlouhy** [comment]
@idlesign What do you mean by that? If other symbols would break the Admin (I will try that), we need to try different approach to fix this. But I don't think, that it is acceptable that any value would break the admin in such way, that the user can't fix his mistake it anymore.

I am probably missing the point of the `current_app_is_admin` note. Those tests in this PR will fail without the fix. The bug doesn't depend on any specifics of my app.

**Comment by PetrDlouhy** [comment]
@idlesign And no, any other symbol that I tried, didn't break the admin, I tried: `$%^čř%*#$@!§¨``°"`. I could add that into the tests also.

**Comment by PetrDlouhy** [comment]
@idlesign And that brings me to the question. Why `django-sitetree` uses rendering of `url` templatetag instead of simple `reverse` here: https://github.com/idlesign/django-sitetree/blob/master/sitetree/sitetreeapp.py#L694?

That is the problem - `'` sign will be interpreted as end of string there.

**Comment by idlesign** [comment]
> I am probably missing the point of the current_app_is_admin note.

Ok, let's try it the other way round: why do you need to resolve tree items URLs in admin at all?

> Why django-sitetree uses rendering of url templatetag [...]

Hard to come back for the exact reasoning from 2010. Most probably it's due to the fact that to exactly mimic the behaviour you ended up with a code copies from various versions of Django (since back then ``url`` tag was not the one we have today.

Nowadays, when 1.7 is the lowest supported version we might indeed try to use ``URLNode`` or even ``reverse`` itself and gain some speed, but one should keep in mind that it needs to be done if a fully backward-compatible manner.

**Comment by PetrDlouhy** [comment]
@idlesign I think, this is some kind of misunderstanding. I don't use `django-sitetree` for generating links inside admin. I am just editing my sitetree there and end up with broken sitetree admin and broken frontend, without any way to take my edit back from admin. See the steps to reproduce in #257.

I cleaned the PR a bit. The problem is that the quotes was not cleaned from `view_path` if the pattern did not contain any parameters. I also added some more test cases.

PS: There is one failing test, but I don't think, that it is caused by this PR.

**Comment by idlesign** [comment]
>  I think, this is some kind of misunderstanding.

Probably. And I undertood #257
The only way to get that exceptionis to hit https://github.com/idlesign/django-sitetree/blob/master/sitetree/sitetreeapp.py#L697
If you hit that line it means sitetree tries to resolve URLs. My point is: there's no need to resolve URL in Admin at all. That's why I've asked 

> why do you need to resolve tree items URLs in admin at all?

Further: if we do not need to resolve in admin, we could bypass resovling, so there'd be no change to brake the Admin. Site itself still could be broken, but that can be fixed, as you've said in Admin.

**Comment by idlesign** [comment]
If you still really want to cure a symptom not the cause, you can do better: no need to strip chars on every call, sanitization on model save would suffice. We could probably also add validation on admin form save, but it won't really add value. 
I'll accept that.

**Comment by timthelion** [comment]
@idlesign 

> Ok, let's try it the other way round: why do you need to resolve tree items URLs in admin at all?

URLs are being resolved in the `tree.html` admin template which is loaded by the `change_form.html` admin template which is loaded by sitetree's `admin.py`.

- https://github.com/idlesign/django-sitetree/blob/master/sitetree/admin.py#L112
- https://github.com/idlesign/django-sitetree/blob/aa25e29a3a4ae58fd415dab302acf5956f13712a/sitetree/templates/admin/sitetree/tree/change_form.html#L47
- https://github.com/idlesign/django-sitetree/blob/aa25e29a3a4ae58fd415dab302acf5956f13712a/sitetree/templates/admin/sitetree/tree/tree.html#L30

**Comment by idlesign** [comment]
@timthelion 
Yeap, that confirms my assumption that URLs in admin are resolved, whereas I suspect they should rather not be. We probably need a change (as stated in https://github.com/idlesign/django-sitetree/pull/258#issuecomment-433707310) in ``SiteTree.url`` that would prevent such resolution while in admin.

**Comment by idlesign** [comment]
`reverse()` based solution (just as @PetrDlouhy mentioned it in https://github.com/idlesign/django-sitetree/pull/258#issuecomment-433710698) is in master at last (see #290). Sorry for such a long delay.

**Comment by PetrDlouhy** [comment]
@idlesign I forgot about this for some time, glad to see, that it is fixed now.
I thing the tests in this PR might be still helpful to ensure that this issue doesn't repeat in the future. Are you interested in porting the tests to newest master?

**Comment by idlesign** [comment]
@PetrDlouhy Sure, PR with test is welcome.

**Pull request closed without merging**
