### PR TITLE
Add extra field to handle get url parameters

### PR DESCRIPTION
**Pull request by sturmf**
This pull request implements an additional field which allows to save get parameters for urls. Those parameters can't be saved in the url parameter, if the url parameter should be resolved by django itself.

Would such a branch have a chance of being merged and what would I need to add to it?

### CODE REVIEW

**Comment by idlesign** [comment]
Can't figure out use cases for this. What are those?

**Comment by sturmf** [comment]
I have the following menu entry: "vegetables". I want to use the Django resolver to not harcode any urls in my menu entries. Therefore I activate the URL as pattern.
But I want the vegetables to be sorted descending which results in an url of the following:

http://myserver/vegetables?sort_order=desc

Where would I put the Get parameters? I can't put it in the URL field. Since the Django resolver can't handle them.

**Comment by idlesign** [comment]
Hm. For this case it's natural to make `desc` ordering the default, so that sorting controls on very page could pass required params.

**Comment by sturmf** [comment]
? how do you mean that, what if I want one link with desc and one with asc.
And it surely should not be part of the URL. (Imho)

**Comment by idlesign** [comment]
I don't get it. Do you have more that one tree item poining to `vegetables` but want them with different sorting?

> And it surely should not be part of the URL. (Imho)

GET param is already a part of an URL.

**Comment by sturmf** [comment]
Yes I have a lot of those links. The links below are just examples. I am building something different then a vegetable database, but thats fine as an example.

http://myserver/vegetables/?sort_order=asc
http://myserver/vegetables/?sort_order=desc
http://myserver/vegetables/?sort_order=asc&color=green
http://myserver/vegetables/?sort_order=asc&color=orange&limit=20

And yeah, those GET parameters could be considered part of the url. But I can't save them in the URL field since the DJANGO resolver tries to match them with the pattern.

**Comment by idlesign** [comment]
Yeah, it will be heck a lot of links especially considering possible params permutations %)
The problem is that all those params are just filters for only one realm, they have very little to do with navigation. Sorry, can't accept it into master. 

Yet solutions are available: custom itee item model, or even dynamic items generation and attachment to existing tree.

**Comment by sturmf** [comment]
Ok sure, I won't try to convince you more than what I already wrote. I just wonder what problems you see with my approach? Maybe others can vote for this pull request if they see fit. If I'm the only one, then I guess it's not worth merging anyways.

**Comment by idlesign** [comment]
Sorry for the delay.

Basically it relates to popularity of such features: sitetree has been around here for quite some time and you're the first one to mention such a use case. As long as the app allows customizations, I can see no real problem here.

And you're right, if this feature in this very implementation is of interest to the large community, it'll accept `urged` label and be merged.

**Comment by idlesign** [comment]
Closed for now, till anyone is interested.

**Pull request closed without merging**
