### PR TITLE
Add kwargs to item creation

### LINKED ISSUE #154: Add kwargs to utils.item to allow passing custom fields
Hi,

I've overridden TreeItem with a custom model to add an Icon field. This all works well at run time, however I'm unable to add the icon in my ``sitetree.py`` file so that fresh installations have the correct icon.

I propose a simple fix would be adding a kwargs parameter to ``utils.item`` method that gets passed to ``get_tree_item_model()``. This way custom fields can be specified at "compile-time" and ``sitetree_resync_apps`` will add the menus exactly as required.

I can provide a pull request if you're interested?

### PR DESCRIPTION
**Pull request by wengole**
Fixes #154

### CODE REVIEW

**Comment by wengole** [comment]
I've tested this on my project, and it worked perfectly.

**Comment by idlesign** [comment]
Nice. Thank you.
Yet I'd like to ask you to make a note on that in docs before merge. Just for people to know how they may deal with such use cases.

**Comment by wengole** [comment]
@idlesign Sure, no problem. I was also looking at the test suite with the intention of adding a test, but I can't see any that already test custom models, and wouldn't know where to begin with that. Any help there would be greatly appreciated.

**Comment by idlesign** [comment]
You can probably test it without a custom model as such, e.g. with `sort_order` kwarg.

**Comment by wengole** [comment]
@idlesign There's a bare minimum test (it makes use of kwargs, but doesn't explicitly test it) that passes. Ideally, given more time, I'd write a full test case for custom models.

**Comment by idlesign** [comment]
Yes, a couple of asserts will certainly do good %)
Take your time.

**Comment by idlesign** [comment]
Note: we actually just need a test checking that values set by custom attributes do not go nowhere %)

**Comment by idlesign** [comment]
Merged. Thank you.

**Pull request merged**
